CREATE TABLE banners (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title1 VARCHAR(255) NOT NULL,
    title2 VARCHAR(255) NOT NULL,
    image VARCHAR(255) NOT NULL, -- اسم فایل تصویر
    is_active BOOLEAN DEFAULT true,
    sort_order INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);